<a href="https://colab.research.google.com/github/dariiimo/nlp2021/blob/main/Lab2/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np, pandas as pd, tensorflow as tf, requests as rqst, io
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from tensorflow.keras import layers

rnd = np.random.randint

folder = '/content/drive/MyDrive/нлп/'

In [4]:
file = open(folder+'100.txt',encoding='windows-1251')
sentences = file.read().split('. ')[:-1]
sentences

['The process of rare disease identification by clinical geneticists is closely associated with the ability to correlate the phenotype of a patient with the relevant genetic syndromes',
 'In order to perform this correlation, the phenotype has to be described in a canonical form or language',
 'Phenotypes such as this are hard to define in a robust manner',
 'In order to build such a system, we decided to focus on facial analysis in our journey to create a leading AI solution using next generation phenotyping (NGP)',
 'With facial recognition one can take as many facial images as needed per person',
 'When aggregating knowledge from clinicians, we noticed that there is an internal bias of ethnicity that is closely associated with certain syndromes, some more than others',
 ' As we maintain the highest privacy and security standards, developers are unable to access user data',
 'Tailoring a solution that combines the components of genomics and AI-based phenotyping is not an easy task an

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Підібрати наукові статті за обраним напрямком англійською мовою, з яких вилучити 100 речень, які найбільш відповідають зазначеному напрямку

In [6]:
sent_df = []
for sent in sentences:
  sent_df.append({'Sentence':sent, 'Label':'Neural network module for recognizing brain diseases'})

sent_df

[{'Label': 'Neural network module for recognizing brain diseases',
  'Sentence': 'The process of rare disease identification by clinical geneticists is closely associated with the ability to correlate the phenotype of a patient with the relevant genetic syndromes'},
 {'Label': 'Neural network module for recognizing brain diseases',
  'Sentence': 'In order to perform this correlation, the phenotype has to be described in a canonical form or language'},
 {'Label': 'Neural network module for recognizing brain diseases',
  'Sentence': 'Phenotypes such as this are hard to define in a robust manner'},
 {'Label': 'Neural network module for recognizing brain diseases',
  'Sentence': 'In order to build such a system, we decided to focus on facial analysis in our journey to create a leading AI solution using next generation phenotyping (NGP)'},
 {'Label': 'Neural network module for recognizing brain diseases',
  'Sentence': 'With facial recognition one can take as many facial images as needed pe

### Створити та зберегти у .csv файл pandas DataFrame з обраних речень із указанням в окремому ствопчику назви напрямку (ця назва має бути однаковою для усіх речень)


In [7]:
sent_df = pd.DataFrame(data=sent_df, columns=['Sentence', 'Label'])

sent_df.to_csv(folder+'100.csv')

sent_df

Sentence                                              Label
0   The process of rare disease identification by ...  Neural network module for recognizing brain di...
1   In order to perform this correlation, the phen...  Neural network module for recognizing brain di...
2   Phenotypes such as this are hard to define in ...  Neural network module for recognizing brain di...
3   In order to build such a system, we decided to...  Neural network module for recognizing brain di...
4   With facial recognition one can take as many f...  Neural network module for recognizing brain di...
..                                                ...                                                ...
95  This includes balancing the prospective benefi...  Neural network module for recognizing brain di...
96  Users report their symptoms into the app, whic...  Neural network module for recognizing brain di...
97  Most common users could be people with serious...  Neural network module for recognizing brain di...
98  Body scans can spot cancer and vascular diseas...  Neural network module for recognizing brain di...
99  Since the first step in health care is compili...  Neural network module for recognizing brain di...

[100 rows x 2 columns]

### Здійснити підготовку набору даних до подальшого моделювання (tokenization&embedding, train_test_split)


### Train/Test Split

In [10]:
from sklearn.model_selection import train_test_split
train_split, test_split = train_test_split(sent_df, train_size=0.9, test_size=0.1)
train_split

Sentence                                              Label
4   With facial recognition one can take as many f...  Neural network module for recognizing brain di...
67  Disease prediction is all about the social imp...  Neural network module for recognizing brain di...
98  Body scans can spot cancer and vascular diseas...  Neural network module for recognizing brain di...
59  Diagnosis and treatment of disease has been at...  Neural network module for recognizing brain di...
42  With the help of machine learning process, str...  Neural network module for recognizing brain di...
..                                                ...                                                ...
39  Some solutions to recognize potential biases a...  Neural network module for recognizing brain di...
17  The solution is adjusted to accurately detect ...  Neural network module for recognizing brain di...
93  AI applications can provide personalized medic...  Neural network module for recognizing brain di...
6    As we maintain the highest privacy and securi...  Neural network module for recognizing brain di...
89  Patient-level data is available in abundance t...  Neural network module for recognizing brain di...

[90 rows x 2 columns]

#### Vectorization

In [11]:
max_tokens = 10000

tokens_count = 0
for sent in sentences:
  tokens_count+=len(sent.split())
avg_tokens = round(tokens_count/len(sentences))
avg_tokens

24

In [12]:
text_vectorizer = TextVectorization(max_tokens=max_tokens, # how many words in the vocabulary (all of the different words in your text)
                                    standardize="lower_and_strip_punctuation", # how to process text
                                    split="whitespace", # how to split tokens
                                    ngrams=None, # create groups of n-words?
                                    output_mode="int", # how to map tokens to numbers
                                    output_sequence_length=avg_tokens, # how long should the output sequence of tokens be?
                                    pad_to_max_tokens=True)
text_vectorizer

In [18]:
text_vectorizer.adapt(sent_df['Sentence'])
text_vectorizer(sent_df['Sentence'])

<tf.Tensor: shape=(100, 24), dtype=int64, numpy=
array([[  2,  53,   4, ...,  27,  10,   2],
       [  6, 126,   5, ...,   0,   0,   0],
       [524,  51,  13, ...,   0,   0,   0],
       ...,
       [ 54, 156, 177, ...,  30, 105,   0],
       [852, 447,  24, ...,   0,   0,   0],
       [194,   2, 145, ...,   8,   2,  54]])>

In [15]:
sent_df

Sentence                                              Label
0   The process of rare disease identification by ...  Neural network module for recognizing brain di...
1   In order to perform this correlation, the phen...  Neural network module for recognizing brain di...
2   Phenotypes such as this are hard to define in ...  Neural network module for recognizing brain di...
3   In order to build such a system, we decided to...  Neural network module for recognizing brain di...
4   With facial recognition one can take as many f...  Neural network module for recognizing brain di...
..                                                ...                                                ...
95  This includes balancing the prospective benefi...  Neural network module for recognizing brain di...
96  Users report their symptoms into the app, whic...  Neural network module for recognizing brain di...
97  Most common users could be people with serious...  Neural network module for recognizing brain di...
98  Body scans can spot cancer and vascular diseas...  Neural network module for recognizing brain di...
99  Since the first step in health care is compili...  Neural network module for recognizing brain di...

[100 rows x 2 columns]

In [19]:
print(f"Most Used: {text_vectorizer.get_vocabulary()[:5]}")
print(f"Most Unused: {text_vectorizer.get_vocabulary()[-5:]}")

Most Used: ['', '[UNK]', 'the', 'and', 'of']
Most Unused: ['abundance', '92', '90', '50', '48']


#### Embedding

In [20]:
embedding = layers.Embedding(input_dim=max_tokens, # set input shape
                             output_dim=128, # set size of embedding vector
                             embeddings_initializer="uniform", # default, intialize randomly
                             input_length=avg_tokens) # how long is each input

embedding(text_vectorizer(sent_df['Sentence']))


<tf.Tensor: shape=(100, 24, 128), dtype=float32, numpy=
array([[[ 0.0411799 , -0.00914962,  0.01756227, ...,  0.04849187,
          0.00837236, -0.00375184],
        [ 0.00563519,  0.0243284 , -0.04215525, ..., -0.04789383,
         -0.0128803 ,  0.03429723],
        [-0.01937166,  0.02174797,  0.00463254, ...,  0.0478951 ,
         -0.04803919, -0.03161398],
        ...,
        [-0.04337077,  0.02537385, -0.0201865 , ...,  0.00080054,
          0.01236407,  0.03228026],
        [ 0.01019882, -0.03203215, -0.01548511, ..., -0.01457093,
          0.04325235, -0.00999046],
        [ 0.0411799 , -0.00914962,  0.01756227, ...,  0.04849187,
          0.00837236, -0.00375184]],

       [[-0.02300379, -0.04081642, -0.03887961, ...,  0.0334788 ,
         -0.02672443, -0.01896499],
        [-0.0096436 , -0.00408442, -0.04703431, ..., -0.00723934,
         -0.02072076,  0.01727821],
        [ 0.02622764, -0.02038053, -0.0378193 , ...,  0.01104288,
         -0.03072879, -0.00937619],
        ...

### Відповіді оформити .ipynb, .csv, .pdf документами